name: demo-streamlit-heroku
channels:
- conda-forge
dependencies:
- python=3.8
- conda
- matplotlib
- numpy
- seaborn
- scipy
- scikit-learn=0.22
- pip
- sklearn
- pip:
  - streamlit
  - scikit-learn
